### ISSUE TITLE
Error in Alexa Service Simulator

### ISSUE THREAD

**Issue by dgabrielli** [timheuer/alexa-skills-dotnet#36]
Hi, I created a simple skill using the alexa-skills-dotnet package and when I test my Lambda function in Lambda directly I get the response I'd expect. When I test the skill from the Alexa Service Simulator I get the following error:

`The remote endpoint could not be called, or the response it returned was invalid.`

Any idea what could be the issue? For reference, the response I get when I test in Lambda directly is:

```json
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "The goal of this is to test my Alexa skill!"
    },
    "card": {
      "type": "Simple",
      "title": "Test Skill Goal",
      "content": "The goal of this is to test my Alexa skill!"
    },
    "shouldEndSession": true
  }
}
```

**Comment by dgabrielli** [comment]
So I did a little more test and when I test in the Alexa Service Simulator using the JSON test rather than the Text test, I get a response:

```json
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "The goal of this is to test my Alexa skill!"
    },
    "card": {
      "content": "The goal of this is to test my Alexa skill!",
      "title": "Test Skill Goal",
      "type": "Simple"
    },
    "reprompt": null,
    "speechletResponse": {
      "outputSpeech": {
        "id": null,
        "ssml": "The goal of this is to test my Alexa skill!"
      },
      "card": {
        "title": "Test Skill Goal",
        "content": "The goal of this is to test my Alexa skill!"
      },
      "directives": null,
      "reprompt": null,
      "shouldEndSession": true
    }
  },
  "sessionAttributes": {}
}
```

**Comment by dgabrielli** [comment]
Here is what I'm seeing in my CloudWatch logs:

```
Error reading date. Unexpected token: Integer. Path 'timestamp', line 4, position 130.: JsonReaderException
at Newtonsoft.Json.JsonReader.ReadAsDateTime()
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Alexa.NET.Request.Type.RequestConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
at lambda_method(Closure , Stream , Stream , ContextInfo )
```

**Comment by dgabrielli** [comment]
I decided to bring in the Alexa.NET library and change the `Timestamp` property in the `Request.Type.Request` object to a `string`, just to see if I would continue to get the same error. When I changed the `Timestamp` property to a `string` everything worked as expected. I'm not sure if this is a Newtonsoft issue or something that needs to be updated in the Alexa.NET library. Or maybe something else?

Any thoughts?

**Comment by stoiveyp** [comment]
Thanks for bringing this to the attention of the library users. My skills are getting the same thing - the request JSON you're seeing in the simulator is not the timestamp you're actually being sent to your skill.

There's an issue in the [Alexa Forums](https://forums.developer.amazon.com/questions/78372/timestamp-is-sent-in-different-formats.html#answer-78408) and I've sent tweets to the Alexa Dev twitter account asking if this is a change in error.

If you hear anything or read anything let me know, obviously I'll do the same.

**Comment by dgabrielli** [comment]
Thanks @stoiveyp! I'll definitely let you know if I hear or see anything.

**Comment by stoiveyp** [comment]
Not a problem @dgabrielli - if you pull #37 and use that with your skill that should resolve the issue until it's been properly reviewed and accepted into the main build.

**Comment by leegreenwood** [comment]
Glad to hear I wasn't the only one getting this issue. Well done guys on getting it moving forward with a resolution.

**Comment by dgabrielli** [comment]
Great! Thanks again @stoiveyp!

**Comment by timheuer** [comment]
I'm inclined to take this fix -- doesn't appear it will affect current users and unblocks some issue.  I don't think we'll hear quickly back from Alexa devs on whether this was expected or not.
