### ISSUE TITLE
Not working with ServiceSimulator

### ISSUE THREAD

**Issue by Serraniel** [timheuer/alexa-skills-dotnet#38]
Hei,

I was using your project in version 1.0.0-beta-9 for while without issues. Then, today, I noticed that the Service Simulator in the testing section of the Alexa Skill is giving the following error if I type in the utterance *start \<appname\>*:
`The remote endpoint could not be called, or the response it returned was invalid.`

In AWS Cloudwatch I saw the following error:
```
Error reading date. Unexpected token: Integer. Path 'timestamp', line 4, position 130.: JsonReaderException
at Newtonsoft.Json.JsonReader.ReadAsDateTime()
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Alexa.NET.Request.Type.RequestConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
at lambda_method(Closure , Stream , Stream , ContextInfo )
```

The JSON generated by the service simulator looks like this:
```json
{
  "session": {
    "sessionId": "SessionId.5e19fbad-549d-4500-96c0-c41dbbc632cc",
    "application": {
      "applicationId": "amzn1.ask.skill.XXXXXX"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.XXXXXX"
    },
    "new": true
  },
  "request": {
    "type": "LaunchRequest",
    "requestId": "EdwRequestId.df44c930-0ca7-4006-9259-ae5370e6fbbc",
    "locale": "de-DE",
    "timestamp": "2017-07-11T07:24:40Z"
  },
  "version": "1.0"
}
```

I checked the nuget packages and updated to version 1.0.1 of the Alexa.NET package and tried again. Still failing, but with another error for the *start \<appname\>* utterance:
```
Value to add was out of range.
Parameter name: value: ArgumentOutOfRangeException
at System.DateTime.Add(Double value, Int32 scale)
at Alexa.NET.Helpers.MixedDateTimeConverter.UtcFromEpoch(Int64 epochTime)
at Alexa.NET.Helpers.MixedDateTimeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Alexa.NET.Request.Type.RequestConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
at lambda_method(Closure , Stream , Stream , ContextInfo )
```

I created a new empty project with a single response to verify this isn´t related to my project. 

**Side fact:** Copy pasting the json into the json tab in the service simulator works. Using the Alexa Echo Dot itself also works. Only the service simulator in text mode generates errors. But if I develop in Office I am unable to use the device as this would annoy my work colleagues.

**Comment by stoiveyp** [comment]
Hi @Serraniel. Thank you for being so clear about the issue an I'm glad that 1.0.1 has been able to fix the issue when interacting with the device itself, but I have the exact same setup with skill development in an open plan office, so I appreciate how frustrating it can be.

My working day has already started but I will try and look into the issue as soon as I can. It's also worth noting that the thread that exists in Amazon Developer Support has had a response from Amazon and they're now asking for skill details of those affected by this timestamp issue so please add your skill details there to gain more visibility.

[Amazon Support: Timestamp is sent in different format](https://forums.developer.amazon.com/questions/78372/timestamp-is-sent-in-different-formats.html)

**Comment by Serraniel** [comment]
Thanks for the feedback. Wasn´t aware that this is such a general issue with the service simulator.

**Comment by timheuer** [comment]
@stoiveyp I guess we need to add that JsonConverter to every timestamp area? The 'start' utterance probably sends something as well.

**Comment by stoiveyp** [comment]
Thankfully the original structure means all the requests share the same Request object, so it should be applied to all the timestamps. Little concerned that it's an OutOfRangeException as that makes me wonder what the simulator is sending that's causing that with an Int64

**Comment by stoiveyp** [comment]
Once I'm out the office tonight I can set up a test skill that accepts the raw JSON to see the differences in CloudWatch and see what we're receiving from the simulator.

**Comment by adriangodong** [comment]
I'm getting the same issue with 1.0.1. Taking a look...

**Comment by adriangodong** [comment]
I believe the root cause is Service Simulator text tab outputs UNIX timestamp **in milliseconds** instead of ISO 8601 format.

**Comment by stoiveyp** [comment]
That'll been an issue with me during testing, thanks for fixing it!
