### ISSUE TITLE
audio response for a specifc intent

### ISSUE THREAD

**Issue by Maria1222w2** [timheuer/alexa-skills-dotnet#64]
I created a skill and I want to give an audio response for an intent. 
Here is the part of my code  SkillResponse = ResponseBuilder.AudioPlayerPlay(PlayBehavior.ReplaceAll,
                    "https://matthiasshapiro.com/alexasamples/First.mp3",
                    "");
and second version that I tried:

var speech = new SsmlOutputSpeech();
                        speech.Ssml = "https://matthiasshapiro.com/alexasamples/First.mp3";
                        returnResponse = ResponseBuilder.Tell(speech);

return SkillResponse;
but in the Logs I am getting these error :
Cannot write a null value for property 'version'. Property requires a value. Path ''.: JsonSerializationException
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
at Amazon.Lambda.Serialization.Json.JsonSerializer.Serialize[T](T response, Stream responseStream)
at lambda_method(Closure , Stream , Stream , ContextInfo )

I tried to use Build a simple voice response - from https://github.com/timheuer/alexa-skills-dotnet.

I really want to manege to create an audio response in C#. Thank you

**Comment by stoiveyp** [comment]
Hi @Maria1222w2 - I created a lambda with the following code which works successfully with version 1.3.0 of Alexa.NET:

```
public SkillResponse FunctionHandler(SkillRequest input, ILambdaContext context)
{
 return ResponseBuilder.AudioPlayerPlay(PlayBehavior.ReplaceAll,
                        "https://matthiasshapiro.com/alexasamples/First.mp3",
                        "testToken");
}
```
If this continues not to work for you, would you be able to send/post your lambda function so we can see the specifics and hopefully get your audio skill working 😄 Thank you!

**Comment by Maria1222w2** [comment]
Thank you very much for your help.
This exemple works for me too. Now, I will try to integrate in my skill workflow.
